stages:
- name: randomgenerator
  dependencies: []
  scheduler:
    scheduler_type: multistep-stage
    parameters:
      inputfile: ../../seed.txt
      numberOfRandoms: [10, 5]
      outputfile: "{workdir}/intermediateResult.txt"
    scatter:
      method: zip
      parameters: [numberOfRandoms]
    step:
      process:
        process_type: 'string-interpolated-cmd'
        cmd: ./../../ran_generator.py {inputfile} {numberOfRandoms} {outputfile}
      environment:
        environment_type: 'docker-encapsulated'
        image: localhost:5000/myfirstimage
      publisher:
        publisher_type: 'interpolated-pub'
        publish:
          output: '{outputfile}'
